name: Docker Build and Push

on:
  # Trigger the workflow on push or commit to any branch
  push:
    branches: [ '*' ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Free disk space
        run: |
          # Display initial disk space
          echo "Initial disk space:"
          df -h
          
          # Remove unnecessary large packages
          echo "Removing unnecessary packages..."
          sudo apt-get remove -y '^ghc-8.*' '^dotnet-.*' '^llvm-.*' '^mongodb-.*' '^mysql-.*' '^php.*' '^docker-.*' || true
          sudo apt-get autoremove -y
          sudo apt-get clean
          
          # Remove unused Docker images, containers, volumes
          echo "Cleaning Docker resources..."
          docker system prune -af || true
          
          # Remove large directories (Android SDK, .NET, etc.)
          echo "Removing large directories..."
          sudo rm -rf /usr/local/lib/android || true
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf /opt/ghc || true
          sudo rm -rf /opt/hostedtoolcache/CodeQL || true
          
          # Display final disk space
          echo "Final disk space:"
          df -h
      
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: hoomanhq/oneclickllm:ollama1
          cache-from: type=gha
          cache-to: type=gha,mode=max