name: Build and Push Docker Image

on:
  push:
    branches: [main, master]
    tags: ['v*']
  workflow_dispatch:

env:
  IMAGE_NAME: oneclickllm
  IMAGE_TAG: "ollamagpu"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Free disk space
        run: |
          echo "Initial disk usage:"
          df -h

          echo "Removing unused packages..."
          sudo apt-get remove -y '^ghc-8.*' '^dotnet-.*' '^llvm-.*' '^mongodb-.*' '^mysql-.*' '^php.*' '^docker-.*' || true
          sudo apt-get autoremove -y
          sudo apt-get clean

          echo "Cleaning Docker system..."
          docker system prune -af || true

          echo "Removing large directories..."
          sudo rm -rf /usr/local/lib/android || true
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf /opt/ghc || true
          sudo rm -rf /opt/hostedtoolcache/CodeQL || true

          echo "Final disk usage:"
          df -h

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Test Docker Hub access
        run: |
          echo "Testing Docker Hub authentication..."
          docker pull hello-world
          docker tag hello-world ${{ vars.DOCKERHUB_USERNAME }}/oneclickllm:test
          docker push ${{ vars.DOCKERHUB_USERNAME }}/oneclickllm:test || echo "Push test failed"

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.io/${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.IMAGE_TAG }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          pull: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 